"""empty message

Revision ID: 02ce83728e72
Revises: 
Create Date: 2020-01-25 20:02:13.312368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ce83728e72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=255), nullable=True),
    sa.Column('lastName', sa.String(length=255), nullable=True),
    sa.Column('roleFr', sa.String(length=255), nullable=True),
    sa.Column('roleEn', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.Text(), nullable=True),
    sa.Column('descriptionFr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manufacturerImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturerId', sa.Integer(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('descriptionEn', sa.Text(), nullable=True),
    sa.Column('descriptionFr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('opening', sa.String(length=255), nullable=True),
    sa.Column('closing', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.Text(), nullable=True),
    sa.Column('descriptionFr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realizationTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realizationTypeEn', sa.String(length=255), nullable=True),
    sa.Column('realizationTypeFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realizationTypeId', sa.Integer(), nullable=True),
    sa.Column('descriptionFr', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.String(length=255), nullable=True),
    sa.Column('projectTypeFr', sa.String(length=255), nullable=True),
    sa.Column('projectTypeEn', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('compartments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=True),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('object_key', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('telephones')
    op.drop_table('resources')
    op.drop_table('realizations')
    op.drop_table('realizationTypes')
    op.drop_table('products')
    op.drop_table('openings')
    op.drop_table('manufacturerImages')
    op.drop_table('manufacturer')
    op.drop_table('locations')
    op.drop_table('employees')
    op.drop_table('emails')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
