"""empty message

Revision ID: 0c33a75a2b93
Revises: 86cb48e55fcc
Create Date: 2020-03-31 21:45:42.447000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c33a75a2b93'
down_revision = '86cb48e55fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblies', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('assemblyTypes', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('emails', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('employees', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('galleries', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('galleryImages', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('jobPostings', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('manufacturer', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('manufacturerImages', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('openings', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('realizationTypes', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('realizations', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('tankerTypes', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('tankers', sa.Column('displayOrder', sa.Integer(), nullable=True))
    op.add_column('telephones', sa.Column('displayOrder', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telephones', 'displayOrder')
    op.drop_column('tankers', 'displayOrder')
    op.drop_column('tankerTypes', 'displayOrder')
    op.drop_column('realizations', 'displayOrder')
    op.drop_column('realizationTypes', 'displayOrder')
    op.drop_column('products', 'displayOrder')
    op.drop_column('openings', 'displayOrder')
    op.drop_column('manufacturerImages', 'displayOrder')
    op.drop_column('manufacturer', 'displayOrder')
    op.drop_column('locations', 'displayOrder')
    op.drop_column('jobPostings', 'displayOrder')
    op.drop_column('galleryImages', 'displayOrder')
    op.drop_column('galleries', 'displayOrder')
    op.drop_column('employees', 'displayOrder')
    op.drop_column('emails', 'displayOrder')
    op.drop_column('assemblyTypes', 'displayOrder')
    op.drop_column('assemblies', 'displayOrder')
    # ### end Alembic commands ###
