"""empty message

Revision ID: 13a6e81432c5
Revises: 5dcfb62cf949
Create Date: 2020-01-18 22:36:40.936000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a6e81432c5'
down_revision = '5dcfb62cf949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realizationTypes', sa.Column('realizationTypeEn', sa.String(length=255), nullable=True))
    op.add_column('realizationTypes', sa.Column('realizationTypeFr', sa.String(length=255), nullable=True))
    op.drop_column('realizationTypes', 'realizationType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realizationTypes', sa.Column('realizationType', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('realizationTypes', 'realizationTypeFr')
    op.drop_column('realizationTypes', 'realizationTypeEn')
    # ### end Alembic commands ###
