"""empty message

Revision ID: 1b58c867ed1d
Revises: 42f554954f30
Create Date: 2020-01-22 18:55:23.490000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b58c867ed1d'
down_revision = '42f554954f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'company')
    # ### end Alembic commands ###
