"""empty message

Revision ID: 259389d5dba1
Revises: deb746fd20a2
Create Date: 2019-12-01 12:58:34.294737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259389d5dba1'
down_revision = 'deb746fd20a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephones')
    op.drop_table('emails')
    op.drop_table('openings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nameEn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nameFr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opening', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('closing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='openings_pkey')
    )
    op.create_table('emails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nameEn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nameFr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='emails_pkey')
    )
    op.create_table('telephones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('locationId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nameEn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nameFr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telephones_pkey')
    )
    # ### end Alembic commands ###
