"""empty message

Revision ID: 46b6ae8b389a
Revises: 1b58c867ed1d
Create Date: 2020-01-22 19:35:04.945000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b6ae8b389a'
down_revision = '1b58c867ed1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('descriptionEn', sa.Text(), nullable=True))
    op.add_column('employees', sa.Column('descriptionFr', sa.Text(), nullable=True))
    op.drop_column('employees', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'descriptionFr')
    op.drop_column('employees', 'descriptionEn')
    # ### end Alembic commands ###
