"""empty message

Revision ID: 5bec4bc8a0ee
Revises: c605c6811eb3
Create Date: 2020-01-25 20:53:32.050250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bec4bc8a0ee'
down_revision = 'c605c6811eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tankerTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tankers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tankerTypeId', sa.Integer(), nullable=True),
    sa.Column('unitId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('kilometers', sa.Integer(), nullable=True),
    sa.Column('engineEn', sa.String(length=255), nullable=True),
    sa.Column('engineFr', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('capacityInLitres', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('noCompartments', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=255), nullable=True),
    sa.Column('dispenser', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('cylinderRefill', sa.String(length=255), nullable=True),
    sa.Column('pump', sa.String(length=255), nullable=True),
    sa.Column('additionalInformationEn', sa.Text(), nullable=True),
    sa.Column('additionalInformationFr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unitId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tankers')
    op.drop_table('tankerTypes')
    # ### end Alembic commands ###
