"""empty message

Revision ID: 5dcfb62cf949
Revises: c0963bb187b4
Create Date: 2020-01-18 22:30:55.325000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dcfb62cf949'
down_revision = 'c0963bb187b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('realizationTypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realizationType', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('realizationTypeId', sa.Integer(), nullable=True),
    sa.Column('projectTypeFr', sa.String(length=255), nullable=True),
    sa.Column('projectTypeEn', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('specification', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('compartments', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('realizations')
    op.drop_table('realizationTypes')
    # ### end Alembic commands ###
