"""empty message

Revision ID: 616bcc2fd777
Revises: 66653f3e4d41
Create Date: 2020-01-25 17:24:27.278309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616bcc2fd777'
down_revision = '66653f3e4d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'resource')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('resource', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
