"""empty message

Revision ID: 66653f3e4d41
Revises: 46b6ae8b389a
Create Date: 2020-01-25 16:55:42.054963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66653f3e4d41'
down_revision = '46b6ae8b389a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.String(length=255), nullable=True),
    sa.Column('descriptionFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
