"""empty message

Revision ID: 6b99a4099184
Revises: 259389d5dba1
Create Date: 2019-12-01 13:08:58.886985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b99a4099184'
down_revision = '259389d5dba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('opening', sa.String(length=255), nullable=True),
    sa.Column('closing', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephones')
    op.drop_table('openings')
    op.drop_table('emails')
    # ### end Alembic commands ###
