"""empty message

Revision ID: 7e81e0069d4d
Revises: c605c6811eb3
Create Date: 2020-01-25 18:36:13.174131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e81e0069d4d'
down_revision = 'c605c6811eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturerImages', sa.Column(
        'descriptionEn', sa.Text(), nullable=True))
    op.add_column('manufacturerImages', sa.Column(
        'descriptionFr', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturerImages', 'descriptionFr')
    op.drop_column('manufacturerImages', 'descriptionEn')
    # ### end Alembic commands ###
