"""empty message

Revision ID: 86cb48e55fcc
Revises: 9bcd91d39520
Create Date: 2020-01-26 12:16:32.268038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86cb48e55fcc'
down_revision = '9bcd91d39520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobPostings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobTitleFr', sa.Text(), nullable=True),
    sa.Column('jobTitleEn', sa.Text(), nullable=True),
    sa.Column('jobSummaryFr', sa.Text(), nullable=True),
    sa.Column('jobSummaryEn', sa.Text(), nullable=True),
    sa.Column('companyDescriptionFr', sa.Text(), nullable=True),
    sa.Column('companyDescriptionEn', sa.Text(), nullable=True),
    sa.Column('jobDescriptionFr', sa.Text(), nullable=True),
    sa.Column('jobDescriptionEn', sa.Text(), nullable=True),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobPostings')
    # ### end Alembic commands ###
