"""empty message

Revision ID: 987eed49ed09
Revises: 6b99a4099184
Create Date: 2019-12-01 19:49:52.497991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987eed49ed09'
down_revision = '6b99a4099184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturerImages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturerId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacturerImages')
    # ### end Alembic commands ###
