"""empty message

Revision ID: 9bc5abee7d2a
Revises: e5fa62f66e5f
Create Date: 2020-04-02 19:37:26.117000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc5abee7d2a'
down_revision = 'e5fa62f66e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('isHtml', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'isHtml')
    # ### end Alembic commands ###
