"""empty message

Revision ID: 9bcd91d39520
Revises: 02ce83728e72
Create Date: 2020-01-25 20:43:51.130000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcd91d39520'
down_revision = '02ce83728e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assemblyTypeId', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.Text(), nullable=True),
    sa.Column('descriptionFr', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assemblyTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleryImages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('galleryId', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galleries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    ) 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assemblyTypes')
    op.drop_table('assemblies')
    op.drop_table('galleries')
    op.drop_table('galleryImages')
    # ### end Alembic commands ###
