"""empty message

Revision ID: a80f659b5923
Revises: 0c33a75a2b93
Create Date: 2020-04-02 16:06:16.907000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80f659b5923'
down_revision = '0c33a75a2b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realizations', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realizations', 'isCertipropane')
    # ### end Alembic commands ###
