"""empty message

Revision ID: c605c6811eb3
Revises: 616bcc2fd777
Create Date: 2020-01-25 17:24:45.868407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605c6811eb3'
down_revision = '616bcc2fd777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('resource', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'resource')
    # ### end Alembic commands ###
