"""Product table

Revision ID: dd7647dffff2
Revises: ef1baae77ff3
Create Date: 2020-01-25 15:49:07.029305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7647dffff2'
down_revision = 'ef1baae77ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('descriptionEn', sa.String(length=255), nullable=True),
    sa.Column('descriptionFr', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
