"""empty message

Revision ID: deb746fd20a2
Revises: db81adbae149
Create Date: 2019-12-01 12:44:54.110837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb746fd20a2'
down_revision = 'db81adbae149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('opening', sa.String(length=255), nullable=True),
    sa.Column('closing', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telephones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('nameEn', sa.String(length=255), nullable=True),
    sa.Column('nameFr', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Telephones')
    op.drop_table('Openings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Openings',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Openings_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('locationId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nameEn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nameFr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('opening', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('closing', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Openings_pkey')
    )
    op.create_table('Telephones',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Telephones_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('locationId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nameEn', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('nameFr', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Telephones_pkey')
    )
    op.drop_table('telephones')
    op.drop_table('openings')
    # ### end Alembic commands ###
