"""Add fileName to product

Revision ID: e3c1048547d8
Revises: 9bc5abee7d2a
Create Date: 2020-04-11 12:39:39.798000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c1048547d8'
down_revision = '9bc5abee7d2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('fileName', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'fileName')
    # ### end Alembic commands ###
