"""empty message

Revision ID: e5fa62f66e5f
Revises: a80f659b5923
Create Date: 2020-04-02 16:17:46.027000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5fa62f66e5f'
down_revision = 'a80f659b5923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblies', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('emails', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('galleryImages', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('openings', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('tankers', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('telephones', sa.Column('isCertipropane', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telephones', 'isCertipropane')
    op.drop_column('tankers', 'isCertipropane')
    op.drop_column('openings', 'isCertipropane')
    op.drop_column('galleryImages', 'isCertipropane')
    op.drop_column('emails', 'isCertipropane')
    op.drop_column('assemblies', 'isCertipropane')
    # ### end Alembic commands ###
