"""empty message

Revision ID: ef1baae77ff3
Revises: 13a6e81432c5
Create Date: 2020-01-18 22:39:14.818000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef1baae77ff3'
down_revision = '13a6e81432c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('realizations', sa.Column('descriptionEn', sa.String(length=255), nullable=True))
    op.add_column('realizations', sa.Column('descriptionFr', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('realizations', 'descriptionFr')
    op.drop_column('realizations', 'descriptionEn')
    # ### end Alembic commands ###
